server:
  error:
    include-stacktrace: on_param


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stochosdb?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format: true


  jackson:
    serialization:
      write_dates_as_timestamps: false
